### ISSUE TITLE
Ability to Change font color and/or background color

### ISSUE THREAD

**Issue by ghost** [bozdoz/msn-history-viewer#2]
Firstly, this is an amazing resource, thank you for taking the time to write it - and apologies if this is no longer an active project but I've been converting my old msn .xml files to .pdf and there are some instances where the font is white and therefore unreadable on the white background.

I'm not sure what causes this, whether I was using a font type that no longer exists or just re-coloured my font to white but I was wondering if there was a workaround please as I'd really love to convert these last few files.

The text is readable when highlighted, but after exporting to .PDF it becomes no longer readable even when highlighted.

**Comment by bozdoz** [comment]
I have no experience with generating pdf's sorry!  What library are you using to do this?

Also did this web app work well for viewing your MSN history?

**Comment by ghost** [comment]
Thanks for replying!

My apologies, when I said exporting to PDF I literally was just using CTRL+P in Chrome and saving as PDF for ease of viewing the future.

It works brilliantly for the most part, I had no issues whatsoever until I encountered this mysterious white text - I've attached a snippet below but had to rename the file extension to .txt as Github wouldn't let me send a .xml file.
[astonvillarox9145851182.txt](https://github.com/bozdoz/msn-history-viewer/files/8730361/astonvillarox9145851182.txt)

I've also just realised from opening this file in notepad that the colour is set to #000000 so perhaps I could simply use Replace-All on all of the affected .xml files to replace this hex-code with something less....white? 🤣

**Comment by bozdoz** [comment]
Oh wow! yeah, looks like the color is white! `color:#ffffff`

So I didn't think about this, but looks like I need to add a background color changer; or maybe foreground colors

**Comment by bozdoz** [comment]
I've added quick toggle to change the font-color to black.  Hope that helps for this particular issue.  I might spare time again later to make an actual color picker or something.

See the circle that hovers over the right-side of the screen:
<img width="545" alt="Screen Shot 2022-05-19 at 9 37 00 PM" src="https://user-images.githubusercontent.com/1410985/169425841-d4996103-91b3-46df-b62d-44b62727d004.png">

**Comment by ghost** [comment]
Amazing, thank you!!
