### ISSUE TITLE
Doesn't support chats in binary format?

### ISSUE THREAD

**Issue by justinlew-is** [bozdoz/msn-history-viewer#3]
I tried uploading the attached chat but it did not appear to work. Perhaps this file type is not supported? Please forgive the absurdity of whatever my young self wrote at the time 😂
[6_8_06@0#38B6.zip](https://github.com/bozdoz/msn-history-viewer/files/10035263/6_8_06%400.38B6.zip)

**Comment by bozdoz** [comment]
No, sorry
